export const ACCESS_TOKEN = 'ACCESS_TOKEN'
export const METHOD_DELETE = 'DELETE'
export const METHOD_PUT = 'PUT'
export const METHOD_GET = 'GET'
export const METHOD_POST = 'POST'
export const COMMON_HANDLE_ERROR = 'COMMON_HANDLE_ERROR'
export const COMMON_SET_SERVER_ERROR = 'COMMON_SET_SERVER_ERROR'
export const COMMON_HIDE_LOADING = 'COMMON_HIDE_LOADING'
export const COMMON_SHOW_LOADING = 'COMMON_SHOW_LOADING'
export const SHOW_ALERT = 'SHOW_ALERT'
export const CLOSE_ALERT = 'CLOSE_ALERT'
export const GET_INFO_USER = 'GET_INFO_USER'
export const GET_INFO_USER_SUCCESS = 'GET_INFO_USER_SUCCESS'

// authentication
export const LOGIN = 'LOGIN'
export const LOG_OUT = 'LOG_OUT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'

// balance
export const CHECK_BALANCE = 'CHECK_BALANCE'
export const CHECK_BALANCE_SUCCESS = 'CHECK_BALANCE_SUCCESS'

// payment request
export const MAKE_PAYMENT_REQUEST = 'MAKE_PAYMENT_REQUEST'
export const MAKE_PAYMENT_REQUEST_SUCCESS = 'MAKE_PAYMENT_REQUEST_SUCCESS'

// cart
export const CART = 'CART'
